// <auto-generated />
using CadeMedicoApi.DATA;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CadeMedicoApi.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("CadeMedicoApi.Models.EspecialidadeModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Especialidades");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Cardiologia"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Obstetrícia"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Pediatria"
                        },
                        new
                        {
                            Id = 4,
                            Nome = "Neurologia"
                        },
                        new
                        {
                            Id = 5,
                            Nome = "Oftalmologia"
                        });
                });

            modelBuilder.Entity("CadeMedicoApi.Models.MedicoCidade", b =>
                {
                    b.Property<int>("MedicoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CidadeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("MedicoId", "CidadeId");

                    b.HasIndex("CidadeId");

                    b.ToTable("MedicoCidade");

                    b.HasData(
                        new
                        {
                            MedicoId = 1,
                            CidadeId = 1
                        },
                        new
                        {
                            MedicoId = 1,
                            CidadeId = 2
                        },
                        new
                        {
                            MedicoId = 3,
                            CidadeId = 3
                        },
                        new
                        {
                            MedicoId = 4,
                            CidadeId = 4
                        },
                        new
                        {
                            MedicoId = 5,
                            CidadeId = 5
                        });
                });

            modelBuilder.Entity("CadeMedicoApi.Models.MedicoEspecialidade", b =>
                {
                    b.Property<int>("MedicoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EspecialidadeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("MedicoId", "EspecialidadeId");

                    b.HasIndex("EspecialidadeId");

                    b.ToTable("MedicoEspecialidade");

                    b.HasData(
                        new
                        {
                            MedicoId = 5,
                            EspecialidadeId = 1
                        },
                        new
                        {
                            MedicoId = 4,
                            EspecialidadeId = 2
                        },
                        new
                        {
                            MedicoId = 3,
                            EspecialidadeId = 3
                        },
                        new
                        {
                            MedicoId = 2,
                            EspecialidadeId = 4
                        },
                        new
                        {
                            MedicoId = 1,
                            EspecialidadeId = 5
                        });
                });

            modelBuilder.Entity("CadeMedicoApi.Models.PrivilegioModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Privilegios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "MASTER"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "ADM"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "USER"
                        },
                        new
                        {
                            Id = 4,
                            Nome = "USERMED"
                        });
                });

            modelBuilder.Entity("CadeMedicoApi.Models.UsuarioModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Login")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<int>("PrivilegioId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Senha")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Login = "nat",
                            Nome = "Natasha",
                            PrivilegioId = 1,
                            Senha = "321"
                        },
                        new
                        {
                            Id = 2,
                            Login = "nishi",
                            Nome = "Shinichi",
                            PrivilegioId = 2,
                            Senha = "124"
                        },
                        new
                        {
                            Id = 3,
                            Login = "Marce",
                            Nome = "Marceline",
                            PrivilegioId = 3,
                            Senha = "852"
                        },
                        new
                        {
                            Id = 4,
                            Login = "lu",
                            Nome = "Luci",
                            PrivilegioId = 4,
                            Senha = "987"
                        },
                        new
                        {
                            Id = 5,
                            Login = "yuyu",
                            Nome = "Yuqui",
                            PrivilegioId = 5,
                            Senha = "526"
                        });
                });

            modelBuilder.Entity("cadeMedicoApi.Models.CidadeModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Estado")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Cidades");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Estado = "PR",
                            Nome = "Londrina"
                        },
                        new
                        {
                            Id = 2,
                            Estado = "PR",
                            Nome = "Rolandia"
                        },
                        new
                        {
                            Id = 3,
                            Estado = "PR",
                            Nome = "Maringá"
                        },
                        new
                        {
                            Id = 4,
                            Estado = "PR",
                            Nome = "Cambé"
                        },
                        new
                        {
                            Id = 5,
                            Estado = "PR",
                            Nome = "Ibipora"
                        });
                });

            modelBuilder.Entity("cadeMedicoApi.Models.MedicoModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Crm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefone")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Medicos");

                    b.HasData(
                        new
                        {
                            id = 1,
                            Crm = "000444",
                            Nome = "Manuel Mejia",
                            Telefone = "984898988"
                        },
                        new
                        {
                            id = 2,
                            Crm = "111222",
                            Nome = "Victor Barros",
                            Telefone = "955554155"
                        },
                        new
                        {
                            id = 3,
                            Crm = "555234",
                            Nome = "Gadiel Mejia",
                            Telefone = "944555868"
                        },
                        new
                        {
                            id = 4,
                            Crm = "050224",
                            Nome = "Adrian Mejia",
                            Telefone = "912346579"
                        },
                        new
                        {
                            id = 5,
                            Crm = "123555",
                            Nome = "Yuqui Maria",
                            Telefone = "983584636"
                        });
                });

            modelBuilder.Entity("CadeMedicoApi.Models.MedicoCidade", b =>
                {
                    b.HasOne("cadeMedicoApi.Models.CidadeModel", "Cidade")
                        .WithMany("MedicoCidade")
                        .HasForeignKey("CidadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("cadeMedicoApi.Models.MedicoModel", "Medico")
                        .WithMany("MedicoCidade")
                        .HasForeignKey("MedicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cidade");

                    b.Navigation("Medico");
                });

            modelBuilder.Entity("CadeMedicoApi.Models.MedicoEspecialidade", b =>
                {
                    b.HasOne("CadeMedicoApi.Models.EspecialidadeModel", "Especialidade")
                        .WithMany("MedicoEspecialidade")
                        .HasForeignKey("EspecialidadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("cadeMedicoApi.Models.MedicoModel", "Medico")
                        .WithMany("MedicoEspecialidade")
                        .HasForeignKey("MedicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Especialidade");

                    b.Navigation("Medico");
                });

            modelBuilder.Entity("CadeMedicoApi.Models.EspecialidadeModel", b =>
                {
                    b.Navigation("MedicoEspecialidade");
                });

            modelBuilder.Entity("cadeMedicoApi.Models.CidadeModel", b =>
                {
                    b.Navigation("MedicoCidade");
                });

            modelBuilder.Entity("cadeMedicoApi.Models.MedicoModel", b =>
                {
                    b.Navigation("MedicoCidade");

                    b.Navigation("MedicoEspecialidade");
                });
#pragma warning restore 612, 618
        }
    }
}
